[documentation] Adicionar a Ata da Quarta Reunião
unb-mds/2023-2-Squad06 pull request #51
Opened 2023-10-23 22:03 UTC by thegm445

# O que este PR introduz?

Closes #47

## Checklist

Por favor, cheque se seu PR atende aos seguintes requisitos:

- [x] Eu atualizei a documentação de acordo (se necessário).
- [x] Eu adicionei testes para cobrir minhas mudanças (se necessário).
- [x] Todos os novos e existentes testes passaram.
- [x] Meu código segue o estilo de código deste projeto.

## Tipo de PR

Que tipo de mudança este PR introduz?

- [ ] Correção de bug
- [ ] Feature request
- [x] Atualização na documentação
- [ ] Atualização no estilo do código (formatação, variáveis locais, etc.)
- [ ] Refatoração (sem mudanças funcionais, sem mudanças na API)
- [ ] Atualizações de dependências
- [ ] Mudanças relacionadas a CI/CD
- [ ] Chore (mudanças não relacionadas a código)
- [ ] Mudanças relacionadas a build (e.g. Dockerfile, pyproject.toml, etc.)

## Este PR introduz uma mudança que quebra a compatibilidade?

- [ ] Sim
- [x] Não

## Outras informações (screenshots, detalhes, etc.)

2023-10-24 22:14 UTC, bitterteriyaki requested changes

2023-10-24 22:14 UTC, bitterteriyaki commented on docs/source/reunioes/atas/reuniao-04.rst
> +as áreas em que cada um trabalhará nessa 'reta final' do projeto e também
```suggestion
as áreas em que cada um trabalhará nessa reta final do projeto e também
```

2023-10-25 01:04 UTC, thegm445 reviewed
LGTM! What about you guys?

2023-10-25 02:56 UTC, bitterteriyaki approved these changes

2023-10-25 02:56 UTC, merged