[bug] Logar automaticamente ao criar uma nova conta
unb-mds/2023-2-Squad06 pull request #81
Opened 2023-11-17 22:35 UTC by LuizaMaluf

# O que este PR introduz?
Close #78 

## Checklist

Por favor, cheque se seu PR atende aos seguintes requisitos:

- [ ] Eu atualizei a documentação de acordo (se necessário).
- [ ] Eu adicionei testes para cobrir minhas mudanças (se necessário).
- [ ] Todos os novos e existentes testes passaram.
- [ ] Meu código segue o estilo de código deste projeto.

## Tipo de PR

Que tipo de mudança este PR introduz?

- [ ] Correção de bug
- [ ] Feature request
- [ ] Atualização na documentação
- [ ] Atualização no estilo do código (formatação, variáveis locais, etc.)
- [ ] Refatoração (sem mudanças funcionais, sem mudanças na API)
- [ ] Atualizações de dependências
- [ ] Mudanças relacionadas a CI/CD
- [ ] Chore (mudanças não relacionadas a código)
- [ ] Mudanças relacionadas a build (e.g. Dockerfile, pyproject.toml, etc.)

## Este PR introduz uma mudança que quebra a compatibilidade?

- [ ] Sim
- [ ] Não

## Outras informações (screenshots, detalhes, etc.)

2023-11-17 23:56 UTC, bitterteriyaki requested changes
Adicionar testes nas linhas indicadas pelo Codecov.

2023-11-19 15:27 UTC, bitterteriyaki requested changes

2023-11-19 15:27 UTC, bitterteriyaki commented on apps/users/tests.py
> +        # para a página inicial após o registro
Não precisa comentar TODA linha. Só aquelas que são realmente difíceis de entender.

2023-11-19 15:27 UTC, bitterteriyaki commented on apps/users/tests.py
> +            self.url, data=self.valid_data, folloe=True
O correto é `follow`.

2023-11-19 15:27 UTC, bitterteriyaki commented on apps/users/tests.py
> +        self.assertTrue(self.client.session["_auth_user_id"])
Tem como melhorar a legibilidade desse código: separe chamadas de métodos em diferentes variáveis para não ficar tudo em uma linha só gigante. Você também consegue evitar chamar `User.objects.get` utilizando o `User.objects.filter` que você havia chamado antes. Adicione também espaçamento entre blocos diferentes de códigos, isso melhora a legibilidade do código:
```suggestion
        user = User.objects.get(username=self.valid_data["username"])

        self.assertRedirects(response, reverse("home"))
        self.assertTrue(user.exists())
      
        # Verifica se o usuário está autenticado após o registro.
        self.client.force_login(user.first())
        self.assertTrue(self.client.session["_auth_user_id"])
```

2023-11-20 15:39 UTC, LuizaMaluf commented on apps/users/tests.py
> +        self.assertTrue(self.client.session["_auth_user_id"])
Usando user = User.objects.get(username=self.valid_data["username"]) a função first( ), da linnha 125, não é reconhecida.

Allém disso, usando a função .exists( ) só funciona se usar user = User.objects.filter(username=self.valid_data["username"]) .

Nesse sentido, fiz algumas alterações.

2023-11-20 15:44 UTC, bitterteriyaki approved these changes
LGTM, TYVM.

2023-11-20 15:44 UTC, merged