Adicionar fomulário inicial de submissão
unb-mds/2023-2-Squad06 pull request #86
Opened 2023-11-21 02:47 UTC by thegm445

# O que este PR introduz?

## Checklist

Por favor, cheque se seu PR atende aos seguintes requisitos:

- [ ] Eu atualizei a documentação de acordo (se necessário).
- [ ] Eu adicionei testes para cobrir minhas mudanças (se necessário).
- [ ] Todos os novos e existentes testes passaram.
- [ ] Meu código segue o estilo de código deste projeto.

## Tipo de PR

Que tipo de mudança este PR introduz?

- [ ] Correção de bug
- [ ] Feature request
- [ ] Atualização na documentação
- [ ] Atualização no estilo do código (formatação, variáveis locais, etc.)
- [ ] Refatoração (sem mudanças funcionais, sem mudanças na API)
- [ ] Atualizações de dependências
- [ ] Mudanças relacionadas a CI/CD
- [ ] Chore (mudanças não relacionadas a código)
- [ ] Mudanças relacionadas a build (e.g. Dockerfile, pyproject.toml, etc.)

## Este PR introduz uma mudança que quebra a compatibilidade?

- [ ] Sim
- [ ] Não

## Outras informações (screenshots, detalhes, etc.)

2023-11-21 13:39 UTC, bitterteriyaki requested changes

2023-11-21 13:39 UTC, bitterteriyaki commented on templates/tasks/detail.html
> +          <input type="submit" class="btn btn-primary" style="width: 100%; margin-top: 25px;" value="Submit">
```suggestion
          <h4>Submit your code!</h4>
          {{ form|crispy }}
          <input
            type="submit"
            class="btn btn-primary"
            style="width: 100%; margin-top: 25px;"
            value="Submit"
          >

2023-11-21 13:39 UTC, bitterteriyaki commented on apps/tasks/views.py
> +            submission.save()
Utilizar a estrutura `Submission.objects.create()`.

2023-11-21 17:58 UTC, bitterteriyaki requested changes

2023-11-21 17:58 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +        )
Testes de inserção devem seguir [esta convenção](https://github.com/unb-mds/2023-2-Squad06/blob/main/apps/users/tests.py#L18-L29).

2023-11-21 20:11 UTC, bitterteriyaki requested changes

2023-11-21 20:11 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +            email="joaozinho@email.com", username="joaozinho", password="senha"
```suggestion
            email="user@email.com", username="user", password="password"
```

2023-11-21 20:12 UTC, bitterteriyaki requested changes

2023-11-21 20:12 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +
Nenhum motivo para criar esses atributos.

2023-11-21 22:20 UTC, thegm445 commented on apps/tasks/tests.py
> +
Para que eu consiga testar o código mais próximo de como será usado, optei por criar todos os objetos (contest, task, user, e etc). Para isso, precisei criar os horários de começo e término do contest.

2023-11-22 00:45 UTC, bitterteriyaki requested changes

2023-11-22 00:45 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +
Eu estava falando do `self.now`, `self.start_time` e `self.end_time`. Você não usa eles em nenhum momento sem ser na função `setUp`.

2023-11-22 00:45 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +        self.assertIsNotNone(self.submission)
Esse teste é irrelevante.

2023-11-22 00:45 UTC, bitterteriyaki commented on apps/tasks/tests.py
> +        )
Esse teste está errado.

2023-11-22 00:45 UTC, bitterteriyaki commented on templates/tasks/detail.html
> +
Não precisa de 2 linhas em branco aqui.

2023-11-22 11:31 UTC, merged